* = $A000
.sbyte "    a game by Peter Hinz / Cerebus      "
.sbyte "Move the ball to stay on the surface.   "
.sbyte "Build up the power bar to make super    "
.sbyte "  jumps with the fire button. More power"
.sbyte "  means a further jump! Fire & pull or  "
.sbyte "  push lets you go backwards.           "
.sbyte "Hit a switch to change a level tile.    "
.sbyte "Jump into a hole to warp to a different "
.sbyte "  location. Maybe!                      "
.sbyte "There are 30 action tiles, find out what"
.sbyte "they do by jumping on them.             "
.sbyte "Hit the tiles in the middle for action. "
.sbyte "Collect points for every tile you hit.  "
.sbyte "Find the END tile to finish the level.  "
.sbyte "Made for the ABBUC Software Contest 2022"
